// src/lib/navbar/Navbar.svelte
<script>
	import NavbarButton from "./NavbarButton.svelte";

</script>

<nav class="navbar glass">
	<NavbarButton herf="#/">Home</NavbarButton>
	<NavbarButton herf="#/about">About</NavbarButton>
	<NavbarButton herf="#/about">About</NavbarButton>
	<NavbarButton herf="#/about">About</NavbarButton>
	<NavbarButton herf="#/about">About</NavbarButton>
	<NavbarButton herf="#/about">About</NavbarButton>
	<NavbarButton herf="#/about">About</NavbarButton>
	<NavbarButton herf="#/about">About</NavbarButton>
	<NavbarButton herf="#/about">About</NavbarButton>
	<NavbarButton herf="#/about">About</NavbarButton>
	<NavbarButton herf="#/about">About</NavbarButton>
	<NavbarButton herf="#/about">About</NavbarButton>
	<NavbarButton herf="#/about">About</NavbarButton>
	<NavbarButton herf="#/about">About</NavbarButton>
</nav>

<style>
	.navbar {
		padding: 0.4rem;
		display: flex;
		gap: 0.2rem;
		position: fixed;
		top: 0;
		left: 0;
		width: 100%;
		z-index: 10;
	}
	a {
		color: white;
		text-decoration: none;
	}
</style>

// src/components/navbar/Navbar.vue
<template>
  <div class="navbar">
    
    <nav>
     <NavbarButton to="/" exact>Home</NavbarButton>
      <NavbarButton to="/about">About</NavbarButton>
      <NavbarButton to="/contact">Contact</NavbarButton>
      <NavbarButton to="/map">Map</NavbarButton>
  
    </nav>
    
  </div>
  
</template>

<script lang="ts">
import NavbarButton from "./NavbarButton.vue";

export default {
  name: "Navbar",
  components: {
    NavbarButton,
  },
};
</script>

<style scoped>
  
.navbar nav {
  display: flex;
  gap: .3rem;
  padding: .3rem;        
  background-color: rgba(64, 64, 64, 0.4);
  backdrop-filter: blur(4px);
  position: relative;
  z-index: 1000;
}

</style>
